### ISSUE TITLE
Menu screen

### ISSUE THREAD

**Issue by dk949** [tacticalhippopotamus/testing-app#1]

**Comment by griggle** [comment]
*Main menu screen with placeholder textures

**Comment by griggle** [comment]
# Problems with current implementation
there are problems with the current core structure of the program. 
## Solutions to the following need to be discussed
1. rendering and updating happens at the same time. idealy objects in the screen would be updated from the bacl of the list to the front, and drawn from the front to the back
2. all objects need to finish updating before any exit checks can happen. could lead to multiple different exit conditions being triggered at once (e.g. change screen to main game, and change screen to options on same frame)
## Possible solutions
1. create a distinction between OTIs that implement drawing behaviour and functional behaviour. create 2 update methods in object, one that calls all drawing OTI methods and one that calls all functional OTI methods. these could then be called separately in different orders.
2. two current ideas:
   1. create an overridable method that is ran after every object update in the object update loop to check for exit conditions. 
        - pros: simple
        - cons: potentially very slow
    2. somehow have an option to pass function pointers, with hardcoded references to screen attributes, to objects
        - pros: idk if it's possible
        - cons: probably a lot faster and much cleaner

# Workarounds that need a cleaner solution
some of the ways functionality is implemented seems more like a workaround than an actual implementation. the following need refactoring into a cleaner solution:
- BaseScreen.screenUpdate() is currently returning a boolean to dermine if the current update loop should end. imo this isn't the best solution and doesn't fit in with the rest of the structure
- to allow for custom screens and objects to run update functionaly other than from OTIs, blank update functions BaseScreen.screenUpdate() and BaseObject.objectUpdate() were created. these seem more like a hacky way to change the fina update methods from their respective classes
